version: '3.7'

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "20091366"
      TELEGRAM_API_HASH: "de0c8975fd6ac8029413fc3c7cb5dbfa"
      TELEGRAM_LOCAL: True
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
      - /mnt/c/data:/media
    ports:
      - "8081:8081"

volumes:
  telegram-bot-api-data: