version: '3.7'

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "20091366"
      TELEGRAM_API_HASH: "de0c8975fd6ac8029413fc3c7cb5dbfa"
      TELEGRAM_LOCAL: True
    volumes:
      - /mnt/c/data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"
  
  telegram-bot:
    image: telegram-video-bot:latest
    environment:
      BOT_TOKEN: ""
      BOT_API: "http://telegram-bot-api:8081"
      ACCESS_IDS: ""
    volumes:
      - /mnt/c/data:/var/lib/telegram-bot-api
      - /mnt/c/media:/data