version: '3.7'

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "TELEGRAM_API_ID"
      TELEGRAM_API_HASH: "TELEGRAM_API_HASH"
      TELEGRAM_LOCAL: True
    volumes:
      - /mnt/c/data/telegram:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"

  telegram-bot:
    image: telegram-video-bot:latest
    environment:
      BOT_TOKEN: "BOT_TOKEN"
      BOT_API: "http://telegram-bot-api:8081"
      ACCESS_IDS: "ACCESS_IDS"
    volumes:
      - /mnt/c/data:/data
